### PR TITLE
M3 fix canvas support detection for older firefox

### PR DESCRIPTION
**Pull request by marfillaster**

### CODE REVIEW

**Comment by MarcDiethelm** [comment]
You appear to have an old version of Shorten. The canvas test currently looks like this...

```
    // test for canvas support

if ( typeof Modernizr != 'undefined' && Modernizr.canvastext ) { // if Modernizr has tested for this already use that.
    is_canvasTextSupported = Modernizr.canvastext;
} else {
    var canvas = document.createElement("canvas");
    is_canvasTextSupported = !!(canvas.getContext && canvas.getContext("2d") && (typeof canvas.getContext("2d").fillText === 'function'));
}
```

**Comment by marfillaster** [comment]
we are using the older version (tag M3) for jQuery 1.3. the current version does not truncate properly in our test case. And we are not using Modernizr

you can just merge it with M3 only

**Comment by MarcDiethelm** [comment]
Can you describe the problem you're seeing and send or link the testcase? Thanks.

**Comment by marfillaster** [comment]
we are using jQuery 1.3.1 no Modernizer. if using the latest shortener the content of the span just continues in one line and overflows outside the fixed width container.

**Comment by MarcDiethelm** [comment]
I tried the Shorten test page with jQuery 1.3.1 just now in Firefox 3.6, Chrome 9, IE 7 and no problems there. Please check the page test/test.html for yourself (you can easily edit it to get jQuery 1.3.1 from Google CDN.) and see if the problem exists there too.
change line 94 and 95:
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.3.1/jquery.js"></script>
If it does I'll need a little more details about your use case (code, what browser, etc) in order to fix the problem..!

**Comment by marfillaster** [comment]
here, what i want to achieve is for the long text 2 wrap to two lines. 

M3 actually rendered correctly
http://jsfiddle.net/VFPj9/

this is the HEAD version
http://jsfiddle.net/c9hc3/

tested in ff 3.6 and chrome 10, unfortunately it's messed up in ie9 latest beta

**Pull request closed without merging**
